DROP DATABASE IF EXISTS recipes_db;
CREATE DATABASE recipes_db;


CREATE TABLE IF NOT EXISTS recipes (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  directions TEXT NOT NULL
);

